# commit para sincronizacao

name: custom_app
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # get_version: ^0.2.0+1
  shared_preferences: ^2.0.4

  #==============================
  #          FIREBASE


  firebase_auth: 3.1.1
  firebase_core: 1.6.0
  firebase_database: 8.0.0 
  # firebase_messaging: 10.0.7
  get: ^3.22.2

  #===============================
  #     PACKAGES PROPRIETARIOS

  custom_auth:
    path:
      ../custom_auth 
  # custom_auth:
  #   git:
  #     url: https://Marcoslima016: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@github.com/Marcoslima016/custom_auth
  #     ref: dev/marcos_lima

  custom_components:
    path:
      ../custom_components  
  # custom_components:
  #   git:
  #     url: https://Marcoslima016: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@github.com/Marcoslima016/custom_components
  #     ref: dev/marcos_lima     


  # enum_from_json:
  #   path:
  #    ../../../enum_from_json
     
  #================================  

  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages