# commit para sincronizacao

name: custom_app
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.4


  get: ^4.7.2

  custom_auth:
    path:
      ../custom_auth 

  custom_components:
    path:
      ../custom_components

  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: